name: Manual docker build deploy

on:
  workflow_dispatch:
    # Enables running the workflow manually
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

jobs:
  test-bash:
    runs-on: self-hosted
    
    steps:
    - name: Print out runner env vars
      shell: bash
      run: |
        echo "Print out runner env vars ..."
        env
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          /*
          !.gitignore
          !.github
    - name: Build, Push and Release a Docker container to Heroku.
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ vars.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web
